export const SET_DONE = 'SET_DONE',
  SET_IMPORTANT = 'SET_IMPORTANT',
  REFRESH_ITEM = 'REFRESH_ITEM ',
  DELETE_ITEM = 'DELETE_ITEM ',
  SET_DATA = 'SET_DATA',
  ADD_VALUE_CHANGED = 'ADD_TODO_CHANGED',
  ITEM_EDIT = 'ITEM_EDIT'